# -*- coding: utf-8 -*-
"""password-checker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Abldvj6qljOKF4WB4pDh9MCqPBWjTS9M
"""

import string

# List of common passwords
COMMON_PASSWORDS = [
    "123456",
    "password",
    "qwerty",
    "12345678",
    "abc123",
    "admin",
    "letmein"
]

def check_password_strength(password):

    if password.lower() in COMMON_PASSWORDS:
        print("\nPassword Strength: VERY WEAK")
        print("Reason: This password is one of the most commonly used passwords.")
        return

    score = 0
    feedback = []

    # Length check
    if len(password) >= 8:
        score += 1
    else:
        feedback.append("- Use at least 8 characters.")

    # Uppercase
    if any(c.isupper() for c in password):
        score += 1
    else:
        feedback.append("- Add at least one uppercase letter.")

    # Lowercase
    if any(c.islower() for c in password):
        score += 1
    else:
        feedback.append("- Add at least one lowercase letter.")

    # Number
    if any(c.isdigit() for c in password):
        score += 1
    else:
        feedback.append("- Add at least one number.")

    # Special Character
    if any(c in string.punctuation for c in password):
        score += 1
    else:
        feedback.append("- Add at least one special character.")

    # Rating
    if score <= 2:
        strength = "Weak"
    elif score <= 4:
        strength = "Medium"
    else:
        strength = "Strong"

    print("\nPassword Strength:", strength)

    if feedback:
        print("\nSuggestions:")
        for item in feedback:
            print(item)
    else:
        print("Excellent! Your password meets all recommended checks.")

# Main Program

password = input("Enter your password: ")
check_password_strength(password)